# v0.4.0 — Mimic, a fully on-chain "Human or AI?" guessing game on GenLayer.
# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }
#
# Each round, the contract shows the player a short, funny one-liner.
# The line was either picked from a curated bank of human-written sentences,
# OR freshly generated by an LLM at round start. The player has to tell which.
#
# Optimistic Democracy: AI validators reach consensus on the LLM JSON output
# (gl.eq_principle.prompt_comparative + structurally validated JSON parse).
from genlayer import *

import json


class Mimic(gl.Contract):
    # State, encoded as comma/JSON strings to keep the schema simple.
    bank:    TreeMap[int, str]    # idx -> sentence
    rounds:  TreeMap[str, str]    # player -> JSON {"persona","sentence","resolved","correct","guess"}
    scores:  TreeMap[str, int]    # player -> cumulative points (int)
    players: DynArray[str]        # all players who ever started a round
    bank_size: int

    def __init__(self) -> None:
        self.bank = TreeMap()
        self.rounds = TreeMap()
        self.scores = TreeMap()
        # Seed the on-chain bank of human-written one-liners.
        sentences = [
            "I told my plant a joke. It didn't leaf an impression.",
            "I'm reading a book on anti-gravity. It's impossible to put down.",
            "Why don't scientists trust atoms? They make up everything.",
            "Parallel lines have so much in common. It's a shame they'll never meet.",
            "My wallet is like an onion. Opening it makes me cry.",
            "I used to play piano by ear, now I use my hands.",
            "Time flies like an arrow. Fruit flies like a banana.",
            "I'm on a seafood diet. I see food and I eat it.",
            "Why did the scarecrow win an award? He was outstanding in his field.",
            "My boss told me to have a good day, so I went home.",
            "I tried to sue the airline for losing my luggage. I lost my case.",
            "The early bird gets the worm, but the second mouse gets the cheese.",
            "I have a fear of speed bumps. I am slowly getting over it.",
            "Did you hear about the claustrophobic astronaut? He just needed space.",
            "I told my wife she draws her eyebrows too high. She looked surprised.",
        ]
        for i in range(len(sentences)):
            self.bank[i] = sentences[i]
        self.bank_size = len(sentences)

    # ── helpers ────────────────────────────────────────────────────────────

    def _pick(self, seed: str) -> dict:
        """Use Optimistic Democracy to pick a persona + (index | ai_sentence) for a round."""
        n = self.bank_size
        prompt = (
            'You run a "Human or AI?" guessing game.\n'
            'Flip a fair coin to pick a persona, then return ONLY JSON in this exact shape:\n'
            '{"persona": "human" | "ai", "index": <int>, "ai_sentence": <string>}\n'
            'Rules:\n'
            '- persona is picked randomly with about 50/50 probability.\n'
            f'- If persona is "human": index is a random integer from 0 to {n - 1} inclusive, '
            'and ai_sentence is the empty string "".\n'
            '- If persona is "ai": write a short, witty, original one-liner '
            '(max 25 words, plain English, no quotes, no labels, no emojis), '
            'and set index to 0.\n'
            f'- Player flavor seed (do not include literally): {seed}\n'
            '- Output JSON only, no prose, no code fences.'
        )

        def call():
            r = gl.nondet.exec_prompt(prompt)
            return r.replace("```json", "").replace("```", "").strip()

        result = gl.eq_principle.prompt_comparative(
            call,
            "Both persona values must match (human or ai).",
        )
        data = json.loads(result)
        persona = data.get("persona")
        if persona != "human" and persona != "ai":
            raise Exception("LLM returned invalid persona")
        if persona == "human":
            idx = data.get("index")
            if not isinstance(idx, int) or idx < 0 or idx >= n:
                raise Exception("LLM returned invalid index")
            return {"persona": "human", "sentence": self.bank[idx]}
        s = data.get("ai_sentence")
        if not isinstance(s, str) or len(s.strip()) < 5:
            raise Exception("LLM returned invalid ai_sentence")
        return {"persona": "ai", "sentence": s.strip()}

    # ── writes ─────────────────────────────────────────────────────────────

    @gl.public.write
    def start_round(self, player: str, seed: str) -> None:
        """Begin a new round for `player`. `seed` is any short string for randomness flavor."""
        if player not in self.scores:
            self.scores[player] = 0
            self.players.append(player)

        picked = self._pick(seed)
        round_state = {
            "persona": picked["persona"],
            "sentence": picked["sentence"],
            "resolved": False,
            "correct": False,
            "guess": "",
        }
        self.rounds[player] = json.dumps(round_state)

    @gl.public.write
    def make_guess(self, player: str, guess: str) -> None:
        normalized = guess.strip().lower()
        if normalized != "human" and normalized != "ai":
            raise Exception('guess must be "human" or "ai"')
        if player not in self.rounds:
            raise Exception("No active round. Call start_round first.")

        state = json.loads(self.rounds[player])
        if state.get("resolved"):
            raise Exception("Already resolved.")

        secret = state.get("persona")
        correct = normalized == secret

        state["guess"] = normalized
        state["correct"] = correct
        state["resolved"] = True
        # Reveal the persona on resolution by leaving it as-is — readers expose it
        # only when resolved=True (see get_my_round).
        self.rounds[player] = json.dumps(state)

        delta = 10 if correct else -5
        self.scores[player] = self.scores[player] + delta

    # ── views ──────────────────────────────────────────────────────────────

    @gl.public.view
    def get_my_round(self, player: str) -> dict:
        if player not in self.rounds:
            return {"active": False}
        state = json.loads(self.rounds[player])
        revealed = state.get("persona", "") if state.get("resolved") else ""
        return {
            "active": True,
            "sentence": state.get("sentence", ""),
            "resolved": bool(state.get("resolved", False)),
            "correct": bool(state.get("correct", False)),
            "guess": state.get("guess", ""),
            "persona": revealed,
        }

    @gl.public.view
    def get_score(self, player: str) -> int:
        return int(self.scores.get(player, 0))

    @gl.public.view
    def get_leaderboard(self) -> list:
        rows = []
        for addr in self.players:
            score = int(self.scores[addr])
            short = addr[:6] + "..." + addr[-4:] if len(addr) > 10 else addr
            rows.append({"player": short, "address": addr, "score": score})
        rows.sort(key=lambda x: -x["score"])
        return rows[:50]

    @gl.public.view
    def has_active_round(self, player: str) -> bool:
        if player not in self.rounds:
            return False
        state = json.loads(self.rounds[player])
        return not bool(state.get("resolved", False))

    @gl.public.view
    def get_bank_size(self) -> int:
        return int(self.bank_size)
