# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }
"""
Mimic — Human or AI?
=====================

A fully on-chain "Human or AI?" guessing game on GenLayer.

Each round, a short one-liner is shown. Either it was picked at random from a
curated bank of human-written sentences, or freshly generated by an LLM at
round start. The player guesses HUMAN or AI.

Optimistic Democracy (gl.vm.run_nondet_unsafe) selects the secret persona and,
when "ai" is chosen, generates the AI sentence. Validators independently
re-run the prompt and the leader's verdict is accepted only when the structure
is valid and personas agree.
"""
from genlayer import *


# ---- Constants ------------------------------------------------------------

# Reward / penalty per guess.
WIN_DELTA: int = 10
LOSS_DELTA: int = 5

# Entry fee per round = 0.0001 GEN (in wei). Small enough to grind, real enough
# to make every guess cost something.
ENTRY_FEE_WEI: int = 10**14

# AI-sentence length bounds (frontend renders the result, so cap to a sane size).
MIN_AI_LEN: int = 5
MAX_AI_LEN: int = 280

# Human-written one-liner bank (deterministic; stored at deploy time).
HUMAN_BANK: tuple = (
    "I told my plant a joke. It didn't leaf an impression.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
    "Why don't scientists trust atoms? They make up everything.",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "My wallet is like an onion. Opening it makes me cry.",
    "I used to play piano by ear, now I use my hands.",
    "Time flies like an arrow. Fruit flies like a banana.",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "My boss told me to have a good day, so I went home.",
    "I tried to sue the airline for losing my luggage. I lost my case.",
    "The early bird gets the worm, but the second mouse gets the cheese.",
    "I have a fear of speed bumps. I am slowly getting over it.",
    "Did you hear about the claustrophobic astronaut? He just needed space.",
    "I told my wife she draws her eyebrows too high. She looked surprised.",
)


class Mimic(gl.Contract):
    # ---- Persistent storage ----------------------------------------------

    # Per-player round state (encoded as compact strings).
    secret: TreeMap[Address, str]         # "human" | "ai"
    sentence: TreeMap[Address, str]       # the line shown to the player
    resolved: TreeMap[Address, u256]      # 0 = active, 1 = resolved
    correct: TreeMap[Address, u256]       # 0 = wrong, 1 = correct
    guess: TreeMap[Address, str]          # "" | "human" | "ai"

    # Per-player counters.
    wins: TreeMap[Address, u256]
    losses: TreeMap[Address, u256]

    # Every player who has ever started a round (for the leaderboard).
    players: DynArray[Address]

    # Global stats.
    total_rounds: u256
    total_fees_wei: u256

    # ---- Constructor ------------------------------------------------------

    def __init__(self) -> None:
        self.total_rounds = u256(0)
        self.total_fees_wei = u256(0)

    # ---- Begin a new round (LLM picks the secret persona) ----------------

    @gl.public.write.payable
    def start_round(self, seed: str) -> None:
        """Pay the entry fee, then pick a secret persona and the sentence to show.

        The leader asks the LLM for a JSON {persona, index, ai_sentence}; validators
        independently re-run the prompt and accept the leader's verdict only when
        their persona matches. The sentence is chosen deterministically from
        HUMAN_BANK[index] (for "human") or from the LLM's ai_sentence (for "ai").
        """
        if int(gl.message.value) < ENTRY_FEE_WEI:
            raise gl.vm.UserError(f"Entry fee is {ENTRY_FEE_WEI} wei (0.0001 GEN)")

        sender = gl.message.sender_address
        self.total_fees_wei = u256(int(self.total_fees_wei) + int(gl.message.value))

        # Register first-time players for the leaderboard.
        if int(self.wins.get(sender, u256(0))) == 0 and int(self.losses.get(sender, u256(0))) == 0 and self.secret.get(sender, "") == "":
            self.players.append(sender)
            self.wins[sender] = u256(0)
            self.losses[sender] = u256(0)

        n = len(HUMAN_BANK)

        prompt = f"""
You are the host of a "Human or AI?" guessing game on GenLayer.

Flip a fair coin to pick a persona, then return ONLY JSON in this exact shape:
{{"persona": "human" | "ai", "index": <int>, "ai_sentence": <string>}}

Rules:
- "persona" must be picked randomly with about 50/50 probability.
- If "persona" is "human": "index" is a random integer in [0, {n - 1}],
  and "ai_sentence" is the empty string "".
- If "persona" is "ai": write a short, witty, original one-liner
  (max 25 words, plain English, no quotes, no labels, no emojis), and
  set "index" to 0.

Player flavor seed (do not include literally): {seed}

Output strictly compact JSON, nothing else.
"""

        def leader_fn() -> dict:
            return gl.nondet.exec_prompt(prompt, response_format="json")

        def validator_fn(leader_result) -> bool:
            if not isinstance(leader_result, gl.vm.Return):
                return False
            data = leader_result.calldata
            if not isinstance(data, dict):
                return False
            persona = data.get("persona", "")
            if persona not in ("human", "ai"):
                return False
            if persona == "human":
                idx = data.get("index", -1)
                if not isinstance(idx, int) or idx < 0 or idx >= n:
                    return False
            else:
                s = data.get("ai_sentence", "")
                if not isinstance(s, str) or len(s.strip()) < MIN_AI_LEN or len(s.strip()) > MAX_AI_LEN:
                    return False
            try:
                mine = leader_fn()
            except Exception:
                return False
            return mine.get("persona", "") == persona

        verdict = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)

        persona = str(verdict["persona"])
        if persona == "human":
            idx = int(verdict["index"])
            if idx < 0 or idx >= n:
                idx = 0
            line = HUMAN_BANK[idx]
        else:
            persona = "ai"
            line = str(verdict.get("ai_sentence", "")).strip()
            if len(line) < MIN_AI_LEN:
                line = "Honestly, I'm just here vibing and pretending to be human."

        self.secret[sender] = persona
        self.sentence[sender] = line
        self.resolved[sender] = u256(0)
        self.correct[sender] = u256(0)
        self.guess[sender] = ""

        self.total_rounds = u256(int(self.total_rounds) + 1)

    # ---- Submit a guess ---------------------------------------------------

    @gl.public.write
    def make_guess(self, guess: str) -> None:
        sender = gl.message.sender_address

        normalized = guess.strip().lower()
        if normalized != "human" and normalized != "ai":
            raise gl.vm.UserError('guess must be "human" or "ai"')

        secret = self.secret.get(sender, "")
        if secret == "":
            raise gl.vm.UserError("No active round. Call start_round() first.")
        if int(self.resolved.get(sender, u256(0))) == 1:
            raise gl.vm.UserError("Round already resolved.")

        is_correct = normalized == secret
        self.guess[sender] = normalized
        self.correct[sender] = u256(1) if is_correct else u256(0)
        self.resolved[sender] = u256(1)

        if is_correct:
            self.wins[sender] = u256(int(self.wins.get(sender, u256(0))) + 1)
        else:
            self.losses[sender] = u256(int(self.losses.get(sender, u256(0))) + 1)

    # ---- Read-only views --------------------------------------------------

    @gl.public.view
    def get_active(self, player_hex: str) -> bool:
        addr = Address(player_hex)
        return self.secret.get(addr, "") != ""

    @gl.public.view
    def get_resolved(self, player_hex: str) -> bool:
        addr = Address(player_hex)
        return int(self.resolved.get(addr, u256(0))) == 1

    @gl.public.view
    def get_sentence(self, player_hex: str) -> str:
        addr = Address(player_hex)
        return self.sentence.get(addr, "")

    @gl.public.view
    def get_persona_revealed(self, player_hex: str) -> str:
        """Returns the secret persona only after the round is resolved."""
        addr = Address(player_hex)
        if int(self.resolved.get(addr, u256(0))) != 1:
            return ""
        return self.secret.get(addr, "")

    @gl.public.view
    def get_guess(self, player_hex: str) -> str:
        addr = Address(player_hex)
        return self.guess.get(addr, "")

    @gl.public.view
    def get_correct(self, player_hex: str) -> bool:
        addr = Address(player_hex)
        return int(self.correct.get(addr, u256(0))) == 1

    @gl.public.view
    def get_wins(self, player_hex: str) -> int:
        addr = Address(player_hex)
        return int(self.wins.get(addr, u256(0)))

    @gl.public.view
    def get_losses(self, player_hex: str) -> int:
        addr = Address(player_hex)
        return int(self.losses.get(addr, u256(0)))

    @gl.public.view
    def get_score(self, player_hex: str) -> int:
        addr = Address(player_hex)
        w = int(self.wins.get(addr, u256(0)))
        l = int(self.losses.get(addr, u256(0)))
        return w * WIN_DELTA - l * LOSS_DELTA

    @gl.public.view
    def get_total_rounds(self) -> int:
        return int(self.total_rounds)

    @gl.public.view
    def get_entry_fee(self) -> int:
        return ENTRY_FEE_WEI

    @gl.public.view
    def get_total_fees(self) -> int:
        return int(self.total_fees_wei)

    @gl.public.view
    def get_player_count(self) -> int:
        return len(self.players)

    @gl.public.view
    def get_leaderboard(self) -> list:
        """Returns [(address_hex, wins, losses, score), ...]. Frontend sorts by score desc."""
        out: list = []
        for addr in self.players:
            w = int(self.wins.get(addr, u256(0)))
            l = int(self.losses.get(addr, u256(0)))
            out.append((str(addr), w, l, w * WIN_DELTA - l * LOSS_DELTA))
        return out
